import __future__
import _warnings
import graphlib
import secrets
import _weakref
import gzip
import select
import _aix_support
import _weakrefset
import hashlib
import selectors
import _ast
import _winapi
import heapq
import setuptools
import _asyncio
import hmac
import shelve
import _bisect
import _zoneinfo
import html
import shlex
import abc
import http
import shutil
import _bootlocale
import aifc
import idlelib
import signal
import _bootsubprocess
import antigravity
import imaplib
import site
import _bz2
import argparse
import imghdr
import smtpd
import _codecs
import array
import imp
import smtplib
import ast
import importlib
import sndhdr
import asynchat
import inspect
import socket
import asyncio
import io
import socketserver
import asyncore
import ipaddress
import sqlite3
import atexit
import itertools
import audioop
import json
import sre_constants
import base64
import keyword
import sre_parse
import _collections_abc
import bdb
import lib2to3
import ssl
import _compat_pickle
import binascii
import linecache
import stat
import _compression
import binhex
import locale
import statistics
import bisect
import logging
import string
import _csv
import builtins
import lzma
import stringprep
import _ctypes
import bz2
import mailbox
import struct
import cProfile
import mailcap
import subprocess
import _decimal
import calendar
import marshal
import sunau
import _distutils_hack
import cgi
import math
import symbol
import _elementtree
import cgitb
import mimetypes
import symtable
import chunk
import mmap
import sys
import _hashlib
import cmath
import modulefinder
import sysconfig
import _heapq
import cmd
import msilib
import tabnanny
import _imp
import code
import msvcrt
import tarfile
import codecs
import multiprocessing
import telnetlib
import _json
import codeop
import netrc
import tempfile
import collections
import nntplib
import textwrap
import colorsys
import this
import _lzma
import compileall
import ntpath
import threading
import _markupbase
import concurrent
import nturl2path
import time
import configparser
import numbers
import timeit
import _msi
import contextlib
import numpy
import tkinter
import contextvars
import opcode
import token
import _multiprocessing
import copy
import operator
import tokenize
import copyreg
import optparse
import trace
import _operator
import os
import traceback
import _osx_support
import csv
import tracemalloc
import _overlapped
import ctypes
import pathlib
import pdb
import turtle
import dataclasses
import pickle
import turtledemo
import _py_abc
import datetime
import pickletools
import types
import _pydecimal
import dbm
import pip
import typing
import _pyio
import decimal
import pipes
import unicodedata
import _queue
import difflib
import pkg_resources
import unittest
import _random
import dis
import pkgutil
import urllib
import distutils
import platform
import uu
import doctest
import plistlib
import uuid
import email
import poplib
import venv
import encodings
import posixpath
import warnings
import ensurepip
import pprint
import wave
import _sitebuiltins
import enum
import profile
import weakref
import _socket
import errno
import pstats
import webbrowser
import _sqlite3
import faulthandler
import winreg
import filecmp
import py_compile
import winsound
import _ssl
import fileinput
import pyclbr
import wsgiref
import _stat
import fnmatch
import pydoc
import xdrlib
import pydoc_data
import xml
import fractions
import pyexpat
import xmlrpc
import _strptime
import ftplib
import queue
import functools
import quopri
import zipapp
import gc
import random
import zipfile
import _thread
import genericpath
import re
import zipimport
import _threading_local
import getopt
import reprlib
import zlib
import _tkinter
import getpass
import rlcompleter
import zoneinfo
import _tracemalloc
import gettext
import runpy
import _uuid
import glob
import sched
while True:
    turtle.forward(random.randrange(1,100))
    turtle.backward(random.randrange(1,100))